#Training
learning_rate: 0.0001
batch_size: 4
weight_decay: 0.01
lr_decay: 0.98
epochs: 100
train_2d: False

# Model
model_name: PLACNet
num_frame: 243
channels: 128
depth: 16

# Data
data_root: data/motion3d/
data_root_2d: data/motion2d/
subset_list: [ H36M-243 ]
dt_file: h36m_sh_conf_cam_source_final.pkl
num_joints: 17
root_rel: True 
add_velocity: False

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_pattern_div: 0.001
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0
lambda_mi: 0.001

# Augmentation
use_proj_as_2d: False
flip: True